[package]
name = "prost-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
prost = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
prost-build = "0.12"